# clusters/k3s-home/flux-system/gotk-sync.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
# ... (rest of the GitRepository is fine)
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  # --- THIS IS THE CRITICAL CHANGE ---
  path: ./clusters/k3s-home/workloads # <-- Change this path
  # -----------------------------------
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
