# clusters/k3s-home/flux-system/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - layers.yaml # Includes infrastructure and apps Kustomizations
  # - kustomization-sources.yaml # Include if sources Kustomization is a separate file