apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
- path: ../flux-patches/kustomize-controller-patch.yaml
  target:
    kind: Deployment
    name: kustomize-controller
    namespace: flux-system
