apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: networking
stringData:
    #ENC[AES256_GCM,data:pzFN96L/pHEXGj2+jTFILXQ8SMNNIdnQOIciIKpueSVxnXJDxA==,iv:pOlrJmd8fUaANHyaEOPor1LrxjVrCeL1ATUO1hn/g48=,tag:pfhz0QFXbVgbkyNOZ79BSA==,type:comment]
    api-token: ENC[AES256_GCM,data:lxNR+ERADxaSRx5TSQQfvFR4bi6t8CiKbo9A1nqnKFNUDRc+CQ1ecg==,iv:ZfbFq9dtyNNb0Dx+3AJ41dGj5d2hqervOkfJqIB6oAE=,tag:6ksFkN4QMtWB3/XCr0UtUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ldyv96p8fpku638mlhgkzv5hjtjyc9krfwnqnx3drqvaf4jq3vyqgxurr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT2xFNlBmVXBGaUFkK0dJ
            UDduVXhJOS9JU0dVV1BwQ0NPMUl4RmFQblN3CkEzSHpTc0Z4V014N1BVclJlODhw
            Q2J6TzJLRURrMTJXcmpNazdGWElkSGsKLS0tIGE0eTVYTGZJVGQwOVI0WlE3UmZk
            ZWdZQnV2UFJ6NVp4YXRVMys2SEkrYU0KGEDg7dZ0+EtCaSPDhdyjxo+mobsSYR6l
            oYOZijYvE0rttpGsbBmrd7Dj6Tll7VMRrSQ3JuGXUPisbOp/4wiZNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-13T20:07:41Z"
    mac: ENC[AES256_GCM,data:KPHLbhABmerlaPI9FvGouHdmNvVIPfMv11xhc+D6pbkOX/2sWom8uh4JzlGfCu32j8JL4+Dii6HJ6rm2babgGurCnMqWHBFdsYS0mSUDeC3M7GGR8e0mjW6e43X8o5GttWNTZD9C4KskzRZfb6691Xw=,iv:S4yq93vHIEGUlcC3mu0M00kAEEUS6rrJTyTsu+ZdrM0=,tag:xiFN9l49sfu1U0SrvairQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1