# clusters/k3s-home/infrastructure/04-gateway/gateway.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: networking # Create a dedicated namespace for this, e.g., 'networking'
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      # This allows any hostname for fletcherlabs.net domain
      hostname: "*.fletcherlabs.net"
      allowedRoutes:
        namespaces:
          from: All