# HTTP to HTTPS redirect for all hosts
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: networking
spec:
  parentRefs:
  - name: main-gateway
    namespace: networking
    sectionName: http
  hostnames:
  - "*.fletcherlabs.net"
  - "fletcherlabs.net"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301