# clusters/k3s-home/infrastructure/04-gateway/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway.yaml
  - wildcard-certificate.yaml
  - cloudflare-api-token-secret.yaml