apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-fletcherlabs-com
  namespace: networking
spec:
  secretName: wildcard-fletcherlabs-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.fletcherlabs.com"
  - "fletcherlabs.com"