apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-fletcherlabs-net
  namespace: networking
spec:
  secretName: wildcard-fletcherlabs-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.fletcherlabs.net"
  - "fletcherlabs.net"