apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - helmrelease.yaml
  - service.yaml
  - secret.yaml

configMapGenerator:
  - name: oauth2-proxy-config
    files:
      - oauth2-proxy.cfg