apiVersion: v1
kind: Secret
metadata:
  name: longhorn-oauth2-proxy-secret
  namespace: longhorn-system
type: Opaque
stringData:
  LONGHORN_OAUTH_CLIENT_SECRET: "PLACEHOLDER_TO_BE_REPLACED"  # Replace with actual secret from Authentik
  LONGHORN_COOKIE_SECRET: "PLACEHOLDER_TO_BE_REPLACED"  # Generate with: openssl rand -base64 32
# Note: This file needs to be encrypted with SOPS before committing
# Commands:
# 1. Generate cookie secret: openssl rand -base64 32
# 2. Get client secret from Authentik after creating the OAuth2 provider
# 3. Replace placeholders above
# 4. Encrypt with SOPS: sops -e -i secret.yaml