apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        containers:
          main:
            enabled: true
            image:
              repository: lscr.io/linuxserver/sabnzbd
              tag: latest
            envFrom:
              - configMapRef:
                  name: rr-env
            lifecycle:
              postStart:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - |
                      # Wait for SABnzbd to create initial config
                      while [ ! -f "/config/sabnzbd.ini" ]; do
                        echo "Waiting for sabnzbd.ini..."
                        sleep 2
                      done
                      sleep 5
                      # Update host_whitelist in the [misc] section
                      if grep -q "^host_whitelist =" /config/sabnzbd.ini; then
                        sed -i '/^\[misc\]/,/^\[/{s/^host_whitelist = .*/host_whitelist = sabnzbd.fletcherlabs.net,/}' /config/sabnzbd.ini
                      else
                        sed -i '/^\[misc\]/a host_whitelist = sabnzbd.fletcherlabs.net,' /config/sabnzbd.ini
                      fi
                      # Restart SABnzbd to apply changes
                      pkill -HUP -f sabnzbd || true
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: true
    service:
      main:
        controller: main
        # Configure as ClusterIP to expose via Cilium ingress
        ports:
          http:
            port: 8080
            targetPort: 8080
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config-pvc
      data:
        enabled: true
        existingClaim: k3s-data-pvc