apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: lscr.io/linuxserver/sabnzbd
      tag: latest
    envFrom:
      - configMapRef:
          name: rr-env
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config-pvc
      temp-downloads:
        enabled: true
        type: hostPath
        hostPath: /mnt/scratch
        mountPath: /data/incomplete
      media:
        enabled: true
        existingClaim: k3s-data-pvc
