apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sabnzbd-http-route
  namespace: media
spec:
  parentRefs:
    - name: main-gateway
      namespace: networking
  hostnames:
    - "sabnzbd.fletcherlabs.com"
  rules:
    - backendRefs:
        - name: sabnzbd
          port: 8080