apiVersion: v1
kind: Secret
metadata:
    name: b2-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:MngATRtV+DORKrp4KnqkdXQBOwOImPSGdOui6nBRqEBKbnbKR/j9g/eSmO7PzrKX2cRlsQXOCwGhDMSdzebET9drklyAeEq6jfkghiK5vl7zRn12VqRqAFsvERWWYhNE/HnuyhV7QIGEEK93,iv:clw80AiV5GDDgvmIv1lufOH0Ivgvh/IXJau9d2IMr2w=,tag:/4tuD2m4aooDr6KFc0fuPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ldyv96p8fpku638mlhgkzv5hjtjyc9krfwnqnx3drqvaf4jq3vyqgxurr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSjdhY0FsdGpzaHh2MVdt
            cFBDRmJoZWxYaE0vTGNwZ0llMTNFOUIralVNCjYxTFAxVGp4d0lLVmNKcDNKTG5x
            bllGcjZqanlBMTBDWVRGdWtRdWNITFEKLS0tIEg5Qkl0bUpyMUI2USt2RE1VQVVB
            cE5NUkpNVWJkZUoyeFl1M08vb3Y1TjQKOmRqQrG+nlP1m71IrHpkV26F7yKOUqiT
            M5JyElMfkkGb4TNnsMMkie+Avh2YaAfmOVzpqRbnSckvPS//w/NvRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-14T01:17:51Z"
    mac: ENC[AES256_GCM,data:H40s3VZdSZWItTpgHDpiHirgVqjp2PpZ7Mf12SpTJbXn/M0fEEvVQ5Pb2vpyvpjV57vbyOVT7gqYt9J4coaJ01+tXTd9GMI/9M0+2VLHgktDRCPJJuGIT1F+Jq2XA2f3WTQs0XIzg5qWUEofLsL6CJrTIQnhzdkbbgVizd47vzY=,iv:8P3ZddmnzmV/77Np9Mm6O1ehi8MRVTapqu1g2vK+Apo=,tag:SsN/W1WNtZr3q+8DgBh3ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
