apiVersion: v1
kind: Secret
metadata:
  name: b2-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=YOUR_B2_KEY_ID_HERE
    aws_secret_access_key=YOUR_B2_APPLICATION_KEY_HERE