apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:H36OOA8hBe1B/hFvaSkIN4ZszyNL7qGUyLOe07oYlZOdX3P89W/nqWg2Rfiy8EY93ETVUvKQybtpo4CGcHe5+rKepKhVfcJ+KHYXBxWhOvDkxeEPi8gAoU4lMR8gTgPa4A==,iv:E4+xYZvKDk32wmHmRMQFzTTS3KL3fc3sz6cLzo22mfU=,tag:wc2YJxE9zliDmChJsy8mZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ldyv96p8fpku638mlhgkzv5hjtjyc9krfwnqnx3drqvaf4jq3vyqgxurr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNnY0SlFSRVVkeG11dUV3
            dk1BdVNCWkhCMy9SSHhMOGtzZVkyZGMzNFFNClhrZU16UUQ3aS81QVFSSzdFWTdy
            ZW1JUEN6K0ZGVkgvQU1DSEpFcU1OaFUKLS0tIHByR2tOK1c3elRQMnhvVFRFQkVL
            dEJRMGdYM1RscTRqSGpjcWNSZUNGZXMK0WCLjKJ+3HcaUb5UeSh38g64R+K5xsUX
            pK1ah+ilcJp+2cAUO6/igVteY5U6kL/ECDsRaQFue++tqIkBVqMfyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-14T05:20:28Z"
    mac: ENC[AES256_GCM,data:CsXzwxlUCKWscyt5fzABYnrZ9HbjaRmajCwXn9OzbhdPly4sItBDeAS3Y4ghy5Q4yFicrcVXYQKJV/7tor92AavmoQ/nevXiA/OCBWblqZILC5a8Xg+rexy16h7NcLEtIRCJPLg0znZ2I6CDGH7JbgjiqQhXCqUkSSvYHfiMyHs=,iv:0LYNbq8wYjT/k2L4JiwpKkSlFyRKfopS+9sALfa6PCc=,tag:f18uaLs5DunkVvIkBNeSiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
