apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:O6FKUR5rUArzyDH9TSItD+rEVSinT0ARAR8Qj6gb3NpIn7ihNKIfSqEXdRAKvkN3EdSwRM884XtfCX7Y+ynXQhaXnkzmqSYzsuZJ8k6L1l6iWDW2,iv:Shv7EnMdg750SCL+YQv3nK7g9gJBvERve3eOotBGPZ0=,tag:qfFwTM2cWrC7Hgr6HM7oPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ldyv96p8fpku638mlhgkzv5hjtjyc9krfwnqnx3drqvaf4jq3vyqgxurr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUjNBOTRuWnZTazJGd1Z5
            eFBDcFJqMVkzVlFoWHNteWc1a2ZSdlJmRndjCjVuN2UwL0R1UFM0RXZxU0tYOUFV
            azZsell2T2ZaYVJyU24xMXhVK05raVEKLS0tIFY1anVnMnpkeElqdEpvb2w0QklR
            U2xLT1FBWkQrQzNzM3UwcTlPb3UzTnMK3bMnQZmC740sYxUBp4b8Abe5OizrULfu
            QlF5b85VL+0xz8QBEb5gYWo6S3mYb1LzQigY3IkPlkOBxC2rhFC+tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-14T05:23:07Z"
    mac: ENC[AES256_GCM,data:+83z0CXAGX9Gm/olaauhbu9/1ccaEEashpoCGDWfM/ntsxJsxx47m5S0isCJ7mFvZET0vFD83KOogyQ1SHAmsg8SUDLPgAxVcvKQ0QBe+wLKC02VUbDBZ3N6m6HDEErOyEyTJayMRBYZ9SEIQQh/evymFoUlhsM4ZNMS1rpFbnc=,iv:wQESJrsJmGaz13HdBWXNREphesJDO8JE/Zfoe/M7G9w=,tag:0qXJWjj6nQc+XnGfPymAsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
