apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:ec8JuNjc5ETPvnowbKvAHMwRBnJln49Png/HFBw2GnctM8HkcBTmP7dp3bMAZrzuVZUgHWC4PmNW/WRoc+Xktnzydb5sJ62JCs95mCkCyhk+o4EiSjYOWg/lDkG6ux4yzQ==,iv:kz6oEL15TgIEOvHU+U+KG5gHCoZzQSLVoKoQBb8E88Y=,tag:6p+IoAKywesEtmqSNtUrNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ldyv96p8fpku638mlhgkzv5hjtjyc9krfwnqnx3drqvaf4jq3vyqgxurr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0L0xsS2tLVlQ5WkhGYlNQ
            dGxacDgyZlh1YmZ1ejhkSkxZSm5EZHY3R3hzCkdhRnpaUWdOVU5OTFR1YUhSWjdy
            WTNHcTRUUCt0SUhmeTRjUW1yZG00RGMKLS0tIEkxNFRHVThRbGFMam90ZjdXOUsz
            MGV6SUZoejJXSGJRWGNqcHhNV2llcDQKf2g3hBUaDbszQ5J2CLHnYBYoyaQwWLJS
            4sctGG/JZQ6w1FxiMOrHXVYGX8G4yhWnhS2th2snfXpEaTq7pcI9XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-13T08:41:34Z"
    mac: ENC[AES256_GCM,data:t2IqLFRKW90dGmmh8y5yRtp+JmLDyduv32uYMCcW8Rv4+PJ/mzc7Ni+hKRKtEHftheSAifj7noayxgFzdUzIfPbJdTjEHVenLZY5cBo1Hb/ol3F7Cde/eOk9WTOunUnIJ26QCVLr2PKLJ/jKLCG+SvS0xZWNQwJ/IOP4omEc0bo=,iv:b4u5fADyXnXB4S/MOo1kPjESdUruHr71znxluEW+wqM=,tag:a3pBnH1GdbzrGH7pJrXhww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
