apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisparr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        pod:
          nodeSelector:
            kubernetes.io/hostname: k3s1  # Run on Dell OptiPlex for better performance
        containers:
          main:
            enabled: true
            image:
              repository: ghcr.io/hotio/whisparr
              tag: v3  # Hotio Whisparr v3
            env:
              - name: WHISPARR__AUTH__METHOD
                value: "none"  # Temporarily disable auth
            envFrom:
              - configMapRef:
                  name: rr-env
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: true
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 2000m
                memory: 1Gi
    service:
      main:
        controller: main
        ports:
          http:
            port: 6969
            targetPort: 6969
            protocol: TCP
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: whisparr-config-pvc
        globalMounts:
          - path: /config
      data:
        enabled: true
        existingClaim: k3s-data-pvc
        globalMounts:
          - path: /data