apiVersion: v1
kind: ConfigMap
metadata:
  name: rr-env       
  namespace: media    
data:
  # --- Your common environment variables ---
  TZ: "America/New_York" 
  PUID: "0"                       
  PGID: "0"                      