apiVersion: v1
kind: ConfigMap
metadata:
  name: rr-env       
  namespace: media    
data:
  # --- Your common environment variables ---
  TZ: "America/New_York" 
  PUID: "1000"                       
  PGID: "1000"
  # Fix s6-overlay permission issues when running as non-root
  S6_READ_ONLY_ROOT: "1"                      