apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media 
resources:
  - namespace.yaml
  - persistent-volume-claims.yaml 
  - common-configmap.yaml       
  - ./radarr                  
  - ./sonarr                    
  - ./lidarr
  - ./prowlarr
  - ./bazarr
  - ./overseerr
  - ./plex
  - ./sabnzbd
  