apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: media
namespace: media
resources:
  - namespace.yaml
  - persistent-volume-claims.yaml
  - common-configmap.yaml
  - ./radarr/helmrelease.yaml
  - ./radarr/ingress.yaml
  - ./sonarr/helmrelease.yaml
  - ./sonarr/ingress.yaml
  - ./lidarr/helmrelease.yaml
  - ./lidarr/ingress.yaml
  - ./bazarr/helmrelease.yaml
  - ./bazarr/ingress.yaml
  - ./overseerr/helmrelease.yaml
  - ./overseerr/ingress.yaml
  - ./plex/helmrelease.yaml
  - ./plex/ingress.yaml
  - ./prowlarr/helmrelease.yaml
  - ./prowlarr/ingress.yaml
  - ./sabnzbd/helmrelease.yaml
  - ./sabnzbd/ingress.yaml
