apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media 
resources:
  - namespace.yaml
  - persistent-volume-claims.yaml 
  - common-configmap.yaml       
  - ./radarr/helmrelease.yaml                  
  - ./sonarr/helmrelease.yaml                    
  - ./lidarr/helmrelease.yaml
  - ./prowlarr/helmrelease.yaml
  - ./bazarr/helmrelease.yaml
  - ./overseerr/helmrelease.yaml
  - ./plex/helmrelease.yaml
  - ./sabnzbd/helmrelease.yaml
  