# Media Stack Kustomization
# This kustomization manages all media-related applications
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This namespace will be applied to all resources below
namespace: media

resources:
  # Base resources for the media namespace
  - namespace.yaml
  - persistent-volume-claims.yaml
  - common-configmap.yaml

  # --- Application Directories ---
  # Kustomize will now look for a 'kustomization.yaml' inside each of these folders.
  - ./bazarr
  - ./lidarr
  - ./overseerr
  - ./plex
  - ./prowlarr
  - ./radarr
  - ./sabnzbd
  - ./sonarr
