apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  # - longhorn-alerts.yaml  # Disabled - Longhorn removed from cluster
  - storage-alerts.yaml
  - velero-alerts.yaml
  - node-alerts.yaml
  - kubernetes-alerts.yaml
  - authentik-alerts.yaml

# Common labels for all alert rules
commonLabels:
  app: kube-prometheus-stack
  prometheus: kube-prometheus-stack-prometheus
  
# Ensure all PrometheusRule resources have the correct labels for discovery
patches:
  - target:
      kind: PrometheusRule
    patch: |
      - op: add
        path: /metadata/labels/prometheus
        value: kube-prometheus-stack-prometheus