apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.16.2"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    # Enable Gateway API support
    featureGates: "ExperimentalGatewayAPISupport=true"
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false # Disabled until monitoring CRDs are installed
    # Ensure cert-manager works with our Pod Security Standards
    global:
      podSecurityPolicy:
        enabled: false
        useAppArmor: false
    # Resource limits for production
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 200m
    webhook:
      timeoutSeconds: 30
      resources:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 128Mi
          cpu: 100m
    cainjector:
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m