apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease-basic.yaml  # Using basic version without monitoring
  - cloudflare-api-token-secret.yaml
  # - letsencrypt-issuer.yaml # Commented out temporarily until cert-manager CRDs are installed