apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jfletcherj86@gmail.net
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        gateway:
          controllerName: gateway.networking.k8s.io/cilium
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jfletcherj86@gmail.net
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        gateway:
          controllerName: gateway.networking.k8s.io/cilium