# clusters/k3s-home/infrastructure-runtime/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # This tells kustomize to look inside these sub-directories
  - ./01-priority-classes
  - ./02-node-labels
  - ./03-storage-pvs
  - ./04-gateway
  - ./05-local-storage