# clusters/k3s-home/workloads/cluster-sync.yaml
# THIS IS THE FULL, CORRECTED VERSION

---
# Layer 0: Sources
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-sources
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-home/apps/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true

---
# Layer 1: CRDs
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure/00-gateway-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-sources

---
# Layer 2a: Install Cilium Chart
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cilium-chart
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure/01-cilium-chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-crds
  wait: true
  timeout: 15m
healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ciliumbgppeeringpolicies.cilium.io
  # ------------------------------------
  - apiVersion: apps/v1
    kind: Deployment
    name: cilium-operator
    namespace: kube-system
  - apiVersion: apps/v1
    kind: DaemonSet
    name: cilium
    namespace: kube-system    
---
# Layer 2b: Configure Cilium BGP
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cilium-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure/01-cilium-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-cilium-chart

---
# Layer 3: Runtime Infrastructure (Gateway Instance & Storage)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-runtime
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure-runtime
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-cilium-config

---
# Layer 4: Applications
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-home/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-runtime
  timeout: 5m
