# clusters/k3s-home/workloads/cluster-sync.yaml
---
# Layer 0: Sources
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: cluster-sources, namespace: flux-system }
spec:
  interval: 10m
  path: ./clusters/k3s-home/apps/sources
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  wait: true
---
# Layer 1: CRDs
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: infra-crds, namespace: flux-system }
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure/00-gateway-api
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  dependsOn: [{ name: cluster-sources }]
---
# Layer 1.5: cert-manager
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: infra-cert-manager, namespace: flux-system }
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure/02-cert-manager
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  dependsOn: [{ name: infra-crds }]
  wait: true
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# Layer 2: Cilium (One single step)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: infra-cilium, namespace: flux-system }
spec:
  interval: 15m
  path: ./clusters/k3s-home/infrastructure/01-cilium # The simplified path
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  dependsOn: 
    - { name: infra-crds }
    - { name: infra-cert-manager } # cert-manager should be ready before Cilium
  wait: true # Wait for the HelmRelease to be ready
  timeout: 15m
---
# Layer 2.4: Node Feature Discovery (Required for GPU plugins)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: infra-nfd, namespace: flux-system }
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure/04-node-feature-discovery
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  dependsOn: [{ name: infra-cilium }]
  wait: true
---
# Layer 2.5: Intel GPU Plugin
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: infra-intel-gpu, namespace: flux-system }
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure/05-intel-gpu-plugin
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  dependsOn: [{ name: infra-nfd }]
---
# Layer 2.6: NVIDIA GPU Plugin
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: infra-nvidia-gpu, namespace: flux-system }
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure/06-nvidia-gpu-plugin
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  dependsOn: [{ name: infra-nfd }]
---
# Layer 3: Runtime Infrastructure
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: infra-runtime, namespace: flux-system }
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure-runtime
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  dependsOn: 
    - { name: infra-intel-gpu } # Depends on Intel GPU plugin
    - { name: infra-nvidia-gpu } # Depends on NVIDIA GPU plugin
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# Layer 4: Applications
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: apps, namespace: flux-system }
spec:
  interval: 10m
  path: ./clusters/k3s-home/apps
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  dependsOn: [{ name: infra-runtime }]
