apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dcgm-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: dcgm-exporter
      version: "3.1.5"
      sourceRef:
        kind: HelmRepository
        name: nvidia-dcgm
        namespace: flux-system
  values:
    # Only run on nodes with NVIDIA GPUs
    nodeSelector:
      kubernetes.io/hostname: k3s3
    
    # Use nvidia runtime for GPU access
    runtimeClassName: nvidia
    
    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    
    # Service configuration
    service:
      type: ClusterIP
      port: 9400
      targetPort: 9400
      name: metrics
    
    # Arguments for the exporter
    arguments:
      - "-f"
      - "/etc/dcgm-exporter/dcp-metrics-included.csv"
    
    # ServiceMonitor for Prometheus scraping
    serviceMonitor:
      enabled: true
      interval: 15s
      additionalLabels:
        release: kube-prometheus-stack
    
    # Security context for GPU access
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
    
    # Environment variables for NVIDIA libraries
    extraEnv:
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: "utility"
      - name: NVIDIA_VISIBLE_DEVICES
        value: "all"