apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-release.yaml
patches:
  - path: daemonset-patch.yaml
    target:
      kind: DaemonSet
      name: dcgm-exporter