apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        containers:
          main:
            enabled: true
            image:
              repository: lscr.io/linuxserver/lidarr
              tag: latest
            envFrom:
              - configMapRef:
                  name: rr-env
    service:
      main:
        controller: main
        # Configure as LoadBalancer to expose via Cilium BGP
        type: LoadBalancer
        annotations:
          # Assign specific IP from Cilium IP pool
          io.cilium/lb-ipam-ips: "192.168.10.46"
        ports:
          http:
            port: 8686
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config-pvc
      data:
        enabled: true
        existingClaim: k3s-data-pvc