# Local MinIO backup storage location
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: minio-local
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero-backups
  config:
    region: us-east-1
    s3ForcePathStyle: "true"
    s3Url: http://minio.velero.svc.cluster.local:9000
  credential:
    name: minio-credentials
    key: cloud
  default: true
---
# Offsite Backblaze B2 backup storage location
# TODO: IMPORTANT - Configure the following before enabling offsite backups:
# 1. Update bucket name to your actual B2 bucket
# 2. Update region to your B2 region (e.g., us-west-004)
# 3. Update s3Url to your B2 endpoint
# 4. Update b2-secret.yaml with real credentials
# 5. Unpause the offsite backup schedules
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: b2-offsite
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: k3s-cluster-backups
  config:
    region: us-west-001
    s3ForcePathStyle: "true"
    s3Url: https://s3.us-west-001.backblazeb2.com
    checksumAlgorithm: ""  # CRITICAL: Empty string for B2 compatibility
    objectLockEnabled: "false"
  credential:
    name: b2-credentials
    key: cloud
  default: false
