# Local Path CSI Volume Snapshot Location
# Note: local-path provisioner doesn't support snapshots
# This is kept as a placeholder for future CSI snapshot support
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: local-path-csi
  namespace: velero
spec:
  provider: csi