apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: SOPS_AGE_KEY_FILE
          value: /etc/sops-keys/age.agekey
        volumeMounts:
        - name: sops-keys
          mountPath: /etc/sops-keys
          readOnly: true
      volumes:
      - name: sops-keys
        secret:
          secretName: sops-age