apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ollama-http-route
  namespace: ai
spec:
  parentRefs:
    - name: main-gateway
      namespace: networking
  hostnames:
    - "ollama.fletcherlabs.net"
  rules:
    - backendRefs:
        - name: ollama
          port: 11434