apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        pod:
          priorityClassName: critical  # High priority for media server
          nodeSelector:
            node-type: compute  # Run on OptiPlex nodes
            workload: light
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - overseerr  # Spread from other light workloads
                    topologyKey: kubernetes.io/hostname
        containers:
          main:
            enabled: true
            image:
              repository: lscr.io/linuxserver/plex
              tag: latest
            envFrom:
              - configMapRef:
                  name: rr-env
            env: []
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: true
            resources:
              requests:
                memory: 2Gi
                cpu: 1
              limits:
                memory: 6Gi
                cpu: 3
    service:
      main:
        controller: main
        # Configure as ClusterIP to expose via Cilium ingress
        ports:
          http:
            port: 32400
            targetPort: 32400
            protocol: TCP
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-pvc
      data:
        enabled: true
        existingClaim: k3s-data-pvc