apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: lscr.io/linuxserver/plex
      tag: latest
    envFrom:
      - configMapRef:
          name: rr-env
    nodeSelector:
      kubernetes.io/hostname: k3s1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k3s1
                    - k3s2
    service:
      main:
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-pvc
      media:
        enabled: true
        existingClaim: k3s-data-pvc
      transcode:
        enabled: true
        type: hostPath
        hostPath: /mnt/transcode
      dri:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
