apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        containers:
          main:
            enabled: true
            image:
              repository: lscr.io/linuxserver/plex
              tag: latest
            envFrom:
              - configMapRef:
                  name: rr-env
            env:
              - name: PLEX_CLAIM
                value: "claim-xCsPBmZf195dCsgmEmUE"
              - name: ADVERTISE_IP
                value: "https://plex.fletcherlabs.net:443"
              - name: PLEX_NO_AUTH_NETWORKS
                value: "192.168.10.0/24"
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: true
    service:
      main:
        controller: main
        # Configure as ClusterIP to expose via Cilium ingress
        ports:
          http:
            port: 32400
            targetPort: 32400
            protocol: TCP
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-pvc
      data:
        enabled: true
        existingClaim: k3s-data-pvc