apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-credentials
  namespace: monitoring
type: Opaque
stringData:
  GRAFANA_OAUTH_CLIENT_SECRET: "PLACEHOLDER_TO_BE_REPLACED"  # Replace with actual secret from Authentik
# Note: This file needs to be encrypted with SOPS before committing
# Commands:
# 1. Get client secret from Authentik after creating the OAuth2 provider
# 2. Replace placeholder above
# 3. Encrypt with SOPS: sops -e -i grafana-oauth-secret.yaml