apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-release.yaml
  - grafana-admin-secret.yaml
  - grafana-httproute.yaml
  - prometheus-httproute.yaml
  # - alerts/  # Temporarily disabled until CRDs are installed
  - alertmanager-config.yaml
  - alertmanager-templates.yaml