apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-release.yaml
  - grafana-admin-secret.yaml
  - grafana-httproute.yaml
  - prometheus-httproute.yaml
  - alerts/  # Include all custom alert rules
  - alertmanager-config.yaml  # Custom Alertmanager configuration
  - alertmanager-templates.yaml  # Alert message templates