apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        pod:
          priorityClassName: critical  # High priority for media server
          # Temporarily disabled until Intel GPU plugin is fixed
          # nodeSelector:
          #   intel.feature.node.kubernetes.io/gpu: "true"  # Match NFD label for Intel GPU nodes
        containers:
          main:
            enabled: true
            image:
              repository: lscr.io/linuxserver/jellyfin
              tag: 10.9.11  # Pinned version for stability
            envFrom:
              - configMapRef:
                  name: rr-env
            env:
              - name: PUID
                value: "1000"  # Drop to this UID after init
              - name: PGID
                value: "1000"  # Drop to this GID after init
              - name: JELLYFIN_PublishedServerUrl
                value: "https://jellyfin.fletcherlabs.net"
              # Intel GPU environment variables
              - name: LIBVA_DRIVER_NAME
                value: "iHD"  # Intel Media Driver for VAAPI
              - name: INTEL_MEDIA_RUNTIME
                value: "VAAPI"
            securityContext:
              runAsUser: 0                     # Must start as root for s6-overlay
              runAsGroup: 0                    # Must start as root for s6-overlay
              runAsNonRoot: false              # Allow root for container init
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: false  # Prevent privilege escalation
              privileged: false                # Critical: No privileged mode
              supplementalGroups: [44, 109]    # video (card0) and render (renderD128) groups
              capabilities:
                drop: ["ALL"]                  # Drop all capabilities
            resources:
              requests:
                memory: 2Gi
                cpu: 1
                # gpu.intel.com/i915: "1"  # Request Intel GPU
              limits:
                memory: 8Gi
                cpu: 4
                # gpu.intel.com/i915: "1"  # Limit Intel GPU
    service:
      main:
        controller: main
        ports:
          http:
            port: 8096
            targetPort: 8096
            protocol: TCP
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-pvc
        globalMounts:
          - path: /config
      data:
        enabled: true
        existingClaim: k3s-data-pvc
        globalMounts:
          - path: /data
      transcode:
        enabled: true
        type: emptyDir
        sizeLimit: 100Gi
        globalMounts:
          - path: /transcode
      cache:
        enabled: true
        type: emptyDir
        sizeLimit: 10Gi
        globalMounts:
          - path: /cache
      # Intel GPU device mounts
      dri:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
            readOnly: false