apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        pod:
          priorityClassName: critical  # High priority for media server
          nodeSelector:
            gpu: nvidia  # Run on the GPU node
          tolerations:
            - key: gpu
              operator: Equal
              value: nvidia
              effect: NoSchedule
        containers:
          main:
            enabled: true
            image:
              repository: lscr.io/linuxserver/jellyfin
              tag: latest
            envFrom:
              - configMapRef:
                  name: rr-env
            env:
              - name: JELLYFIN_PublishedServerUrl
                value: "https://jellyfin.fletcherlabs.net"
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: true
              privileged: true  # Required for GPU access
            resources:
              requests:
                memory: 2Gi
                cpu: 1
                nvidia.com/gpu: 1  # Request 1 NVIDIA GPU
              limits:
                memory: 8Gi
                cpu: 4
                nvidia.com/gpu: 1  # Limit to 1 NVIDIA GPU
    service:
      main:
        controller: main
        ports:
          http:
            port: 8096
            targetPort: 8096
            protocol: TCP
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-pvc
        globalMounts:
          - path: /config
      data:
        enabled: true
        existingClaim: k3s-data-pvc
        globalMounts:
          - path: /data
      transcode:
        enabled: true
        type: emptyDir
        sizeLimit: 100Gi
        globalMounts:
          - path: /transcode
      cache:
        enabled: true
        type: emptyDir
        sizeLimit: 10Gi
        globalMounts:
          - path: /cache
      # NVIDIA GPU device mounts
      nvidia:
        enabled: true
        type: hostPath
        hostPath: /dev/nvidia0
        globalMounts:
          - path: /dev/nvidia0
      nvidia-uvm:
        enabled: true
        type: hostPath
        hostPath: /dev/nvidiactl
        globalMounts:
          - path: /dev/nvidiactl
      nvidia-uvm-tools:
        enabled: true
        type: hostPath
        hostPath: /dev/nvidia-uvm
        globalMounts:
          - path: /dev/nvidia-uvm
      nvidia-uvm-modeset:
        enabled: true
        type: hostPath
        hostPath: /dev/nvidia-uvm-tools
        globalMounts:
          - path: /dev/nvidia-uvm-tools