apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        containers:
          main:
            enabled: true
            image:
              repository: lscr.io/linuxserver/jellyfin
              tag: latest
            envFrom:
              - configMapRef:
                  name: rr-env
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 8096
            targetPort: 8096
            protocol: TCP
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-pvc
      data:
        enabled: true
        existingClaim: k3s-data-pvc