apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Optional: Set default namespace for resources listed below
# namespace: monitoring

# List the YAML files or subdirectories containing Kustomizations within THIS directory
resources:
  - namespace.yaml
  - oauth2-proxy-prometheus
  # Add other monitoring resources here later:
  # - prometheus-helmrelease.yaml
  # - grafana-helmrelease.yaml