apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy-longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.7.1"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      existingSecret: oauth2-proxy-longhorn-secret
      configFile: |-
        email_domains = [ "*" ]
        upstreams = [ "http://longhorn-frontend:80" ]
        provider = "oidc"
        oidc_issuer_url = "https://authentik.fletcherlabs.net/application/o/longhorn/"
        redirect_url = "https://longhorn.fletcherlabs.net/oauth2/callback"
        cookie_secure = true
        cookie_domains = [".fletcherlabs.net"]
        cookie_expire = "24h"
        cookie_refresh = "1h"
        skip_provider_button = true
        pass_authorization_header = true
        pass_access_token = true
        pass_user_headers = true
        set_authorization_header = true
        set_xauthrequest = true
        silence_ping_logging = true
        
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.6.0
      
    service:
      type: ClusterIP
      portNumber: 80
      
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
        
    replicaCount: 2
    
    hostAliases:
      - ip: "192.168.10.224"
        hostnames:
          - "authentik.fletcherlabs.net"
    
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - oauth2-proxy
              topologyKey: kubernetes.io/hostname
