apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-setup
  namespace: networking
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000
    users:
      - name: admin
        password: $2y$10$EFmogJJPn5HSBqfLbXlXhOC3OUI9Y7daLB3HXa3kNmvYbMJqSs7u2  # changeme
    auth_attempts: 5
    block_auth_min: 15
    http_proxy: ""
    language: en
    theme: auto
    debug_pprof: false
    web_session_ttl: 720
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53
      anonymize_client_ip: false
      protection_enabled: true
      blocking_mode: default
      blocking_ipv4: ""
      blocking_ipv6: ""
      blocked_response_ttl: 10
      protection_disabled_until: null
      parental_block_host: family-block.dns.adguard.com
      safebrowsing_block_host: standard-block.dns.adguard.com
      ratelimit: 0
      ratelimit_whitelist: []
      refuse_any: true
      upstream_dns:
        - 192.168.1.1  # Your router first
        - 8.8.8.8
        - 8.8.4.4
      upstream_dns_file: ""
      bootstrap_dns:
        - 9.9.9.10
        - 149.112.112.10
        - 2620:fe::10
        - 2620:fe::fe:10
      fallback_dns: []
      all_servers: false
      fastest_addr: false
      fastest_timeout: 1s
      allowed_clients: []
      disallowed_clients: []
      blocked_hosts:
        - version.bind
        - id.server
        - hostname.bind
      trusted_proxies:
        - 127.0.0.0/8
        - ::1/128
      cache_size: 4194304
      cache_ttl_min: 0
      cache_ttl_max: 0
      cache_optimistic: false
      bogus_nxdomain: []
      aaaa_disabled: false
      enable_dnssec: false
      edns_client_subnet:
        custom_ip: ""
        enabled: false
        use_custom: false
      max_goroutines: 300
      handle_ddr: true
      ipset: []
      ipset_file: ""
      bootstrap_prefer_ipv6: false
      filtering_enabled: true
      filters_update_interval: 24
      parental_enabled: false
      safebrowsing_enabled: false
      safebrowsing_cache_size: 1048576
      safesearch_cache_size: 1048576
      parental_cache_size: 1048576
      cache_time: 30
      filters:
        - enabled: true
          url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
          name: AdGuard DNS filter
          id: 1
        - enabled: false
          url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
          name: AdAway Default Blocklist
          id: 2
      whitelist_filters: []
      user_rules:
        # Force all fletcherlabs.net domains to resolve locally
        - "@@||fletcherlabs.net^$dnsrewrite=192.168.10.224"
        - "@@||*.fletcherlabs.net^$dnsrewrite=192.168.10.224"
      dhcp:
        enabled: false
      clients:
        runtime_sources:
          whois: true
          arp: true
          rdns: true
          dhcp: true
          hosts: true
        persistent: []
      log_file: ""
      log_max_backups: 0
      log_max_size: 100
      log_max_age: 3
      log_compress: false
      log_localtime: false
      verbose: false
      os:
        group: ""
        user: ""
        rlimit_nofile: 0
      schema_version: 28