apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sonarr-http-route
  namespace: media
spec:
  parentRefs:
    - name: main-gateway
      namespace: networking
      sectionName: https
  hostnames:
    - "sonarr.fletcherlabs.net"
  rules:
    - backendRefs:
        - name: sonarr
          port: 8989