apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-gpu
  namespace: intel-device-plugins-system
spec:
  interval: 5m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    name: intel-gpu-plugin
    sharedDevNum: 10  # Allow multiple containers to share GPU
    nodeFeatureRule: true
    # The device plugin DaemonSet will run on all nodes
    # but only expose GPU resources on nodes that have Intel GPUs