apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: intel-device-plugins-system
spec:
  interval: 5m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    manager:
      enabled: true