# Cilium BGP Peering Configuration
# This policy configures BGP peering between Cilium and your router
#
# IMPORTANT: For BGP to work, you must label your nodes with:
# kubectl label node <node-name> bgp=enabled
#
# clusters/k3s-home/infrastructure/01-cilium/bgp-peering.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering
  # namespace: kube-system # Not needed, it's a cluster-scoped resource
spec:
  nodeSelector:
    matchLabels:
      bgp: enabled # Keep this, and remember to label your node(s)!
  virtualRouters:
  - localASN: 64512
    # CHANGED: Set to false for simplicity. You only need to advertise LB IPs.
    exportPodCIDR: false
    neighbors:
      - peerAddress: "192.168.1.1/32"
        peerASN: 64513