apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering
  namespace: kube-system
spec:
  #── Select the nodes running Cilium ──
  nodeSelector:
    matchLabels:
      bgp: enabled

  virtualRouters:
  - name: default
    # Your cluster’s ASN (from Helm values default or override)
    localASN: 65001      
    # Export both Pod- and Service- CIDRs
    exportPodCIDR: true
    exportServiceCIDR: true

    neighbors:
    - peerAddress: "192.168.1.1"  # UDM-SE BGP IP
      peerASN:    64512          # UDM-SE ASN
