# Cilium BGP Peering Configuration
# This policy configures BGP peering between Cilium and your router
#
# IMPORTANT: For BGP to work, you must label your nodes with:
# kubectl label node <node-name> bgp=enabled
#
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering
  namespace: kube-system
spec:
  # Match the nodes where Cilium should speak BGP
  # Only nodes with the label 'bgp=enabled' will peer
  nodeSelector:
    matchLabels:
      bgp: enabled

  virtualRouters:
  - localASN: 64512         # Cilium's Autonomous System Number
    exportPodCIDR: true     # Advertise pod network to BGP peer
    # serviceSelector: {}   # Disabled - using L2 for LoadBalancer services
    neighbors:
      - peerAddress: "192.168.1.1/32"  # Router's BGP IP (UDM-SE)
        peerASN: 64513                 # Router's Autonomous System Number
