apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering
  namespace: kube-system
spec:
  # Match the nodes where Cilium should speak BGP
  nodeSelector:
    matchLabels:
      bgp: enabled

  virtualRouters:
  - localASN: 64512         # your Cilium ASN
    exportPodCIDR: true
    serviceSelector: {} # Export all services
    neighbors:
      - peerAddress: "192.168.1.1"  # UDM-SE BGP IP as CIDR
        peerASN:    64513
