apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering
spec:
  virtualRouters:
  - localASN: 64512  
    exportPodCIDR: false
    neighbors:
    - peerAddress: "192.168.1.1/32"
      peerASN: 64513
    serviceSelector:
      matchLabels:
        bgp: enabled