apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering
  namespace: kube-system
spec:
  # Select all nodes labeled “bgp=enabled”
  nodeSelector:
    matchLabels:
      bgp: enabled

  virtualRouters:
  - localASN: 65001        
    exportPodCIDR: true    # advertise Pod CIDRs only
    neighbors:
      - peerAddress: "192.168.1.1"  # UDM-SE BGP IP
        peerASN:    64512           # UDM-SE ASN
