# clusters/k3s-home/infrastructure/01-cilium/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      # Using latest stable Cilium version
      version: "1.17.4"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation: 
      retries: 3
    # Tell Flux to adopt the existing Helm release
    replace: true
  upgrade:
    remediation: 
      retries: 3
  values:
    # Base K3s/CNI settings
    k8sServiceHost: "192.168.10.30"
    k8sServicePort: 6443
    cni:
      install: true
      exclusive: true
      binPath: /var/lib/rancher/k3s/data/current/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
    
    # Core Features
    kubeProxyReplacement: true
    operator: 
      replicas: 1
    
    # Enable Gateway API support
    gatewayAPI: 
      enabled: true
    
    # Load Balancer configuration
    loadBalancer:
      mode: "snat"  # Changed from dsr to snat for compatibility with vxlan
      l7: 
        backend: "envoy"
    
    # Hubble monitoring
    hubble:
      enabled: true
      ui: 
        enabled: true
      relay: 
        enabled: true

    # Enable BGP Control Plane (configuration via CRDs)
    bgpControlPlane:
      enabled: true
      
    # IPAM Configuration
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]

    # Enable L2 announcements (configuration via CRDs)
    l2announcements:
      enabled: true