# clusters/k3s-home/infrastructure/01-cilium-chart/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: "1.15.5" # Using a known stable version
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
  values:
    # --- Base K3s/CNI settings ---
    k8sServiceHost: "192.168.10.30"
    k8sServicePort: 6443
    cni:
      install: true
      exclusive: true
      binPath: /var/lib/rancher/k3s/data/current/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
    
    # --- Core Features ---
    kubeProxyReplacement: true
    operator: { replicas: 1 }
    gatewayAPI: { enabled: true }
    loadBalancer:
      mode: "dsr"
      l7: { backend: "envoy" }
    hubble:
      enabled: true
      ui: { enabled: true }
      relay: { enabled: true }

    # ===================================================================
    # --- THIS IS THE SOLUTION: BGP & L2 Config is now inside Helm ---
    # ===================================================================
    bgpControlPlane:
      enabled: true
      
    bgp:
      enabled: true # Keep this separate from bgpControlPlane
      announce:
        loadbalancerIPs: true
        podCIDR: false # Usually false for home labs

    l2announcements:
      enabled: true
      
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]
      pools:
        # This defines the IP pool for your LoadBalancer services
        - name: primary-pool
          ipv4:
            cidrs:
              - cidr: "192.168.10.230/28" # e.g., 192.168.10.230 - 192.168.10.245
                
    # This defines the BGP Peering relationship
    bgpPeering:
      # This policy applies to all nodes with the 'bgp=enabled' label
      nodeSelector:
        matchLabels:
          bgp: enabled
      peers:
        - peerAddress: "192.168.1.1" # Your UDM SE's IP
          peerAsn: 64513           # Your UDM SE's ASN
          localAsn: 64512          # Your K3s cluster's ASN
          
    # This defines the L2 Announcement policy
    l2PodAnnouncements:
      # This links the L2 announcements to the IP pool we defined above
      ipPoolSelector:
        matchLabels:
          "io.cilium.ipam.pool": "primary-pool"
      # And defines which network interfaces to use
      interfaceSelector:
        matchNames:
          - "enx.+" # Your USB 2.5Gbe dongles
