apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  # ── Give the entire release up to 15 minutes for any Helm action ──
  timeout: 15m0s
  interval: 5m

  chart:
    spec:
      chart: cilium
      version: "1.17.3"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 15m
      reconcileStrategy: ChartVersion

  install:
    crds: CreateReplace
    remediation:
      retries: 5

  upgrade:
    # ── Allow upgrades up to 15 minutes ──
    timeout: 15m0s
    # ── Don’t wait on CRD hooks or pod readiness (bypass failing probes) ──
    disableWait: true           # Disables waiting for resources to be ready :contentReference[oaicite:0]{index=0}
    disableWaitForJobs: true    # Disables waiting for Jobs to complete :contentReference[oaicite:1]{index=1}
    crds: CreateReplace
    remediation:
      retries: 5
      remediateLastFailure: true

  values:
    # ── RBAC / ServiceAccount ──
    rbac:
      create: true
    serviceAccounts:
      cilium:
        create: true
        name: cilium
      operator:
        create: true
        name: cilium-operator

    # ── Base K3s/CNI settings ──
    k8sServiceHost: "192.168.10.30"
    k8sServicePort: 6443
    cni:
      install: true
      exclusive: true
      binPath: /var/lib/rancher/k3s/data/current/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d

    operator:
      replicas: 1

    # ── Core features ──
    kubeProxyReplacement: true
    bgpControlPlane:
      enabled: true

    loadBalancer:
      mode: snat
    l2announcements:
      enabled: true
    serviceExternalIPs:
      enabled: true

    ingressController:
      enabled: true
      loadbalancerMode: dedicated
      service:
        type: LoadBalancer

    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_app,destination_ip,destination_namespace,destination_app,traffic_direction
