# clusters/k3s-home/infrastructure/01-cilium-chart/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: "1.15.5" # Using a known stable version
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
values:
  # Base K3s/CNI settings
  k8sServiceHost: "192.168.10.30"
  k8sServicePort: 6443
  cni:
    install: true
    exclusive: true
    binPath: /var/lib/rancher/k3s/data/current/bin
    confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
  
  # Core Features
  kubeProxyReplacement: true
  operator: { replicas: 1 }
  gatewayAPI: { enabled: true }
  loadBalancer:
    mode: "dsr"
    l7: { backend: "envoy" }
  hubble:
    enabled: true
    ui: { enabled: true }
    relay: { enabled: true }

  # --- BGP & IPAM Configuration ---
  bgpControlPlane:
    enabled: true

  ipam:
    mode: "cluster-pool" # This is required for BGP
    operator:
      clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]

  # This is the single, top-level block for BGP configuration
  bgp:
    enabled: true
    announce:
      loadbalancerIPs: true # This explicitly enables LB IP announcements
      podCIDR: false
    
    # This defines the BGP Peering relationship
    peers:
      - name: udm-se
        peerAddress: "192.168.1.1/32" # Your UDM SE's IP
        peerAsn: 64513               # Your UDM SE's ASN
        localAsn: 64512              # Your K3s cluster's ASN

  # This is the single, top-level block for L2 Announcements
  l2announcements:
    enabled: true
    # This links the L2 announcements to the IP pool we defined below
    ipPools:
    - name: primary-pool
      selector:
        matchLabels:
          "io.cilium.ipam.pool": "primary-pool"
      # And defines which network interfaces to use
      interfaces:
      - "^enx.+"

  # This defines the IP pool for your LoadBalancer services
  ipamPools:
    enabled: true
    pools:
    - name: primary-pool
      cidrs:
        - cidr: "192.168.10.230/28"