apiVersion: helm.toolkit.fluxcd.io/v2beta2 # Or v2beta1 if using older Flux
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system # Cilium components will be installed in kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium # The name of the chart in the repository
      version: "1.15.3" # Specify a VALID Cilium version (e.g., 1.14.5, 1.15.3)
      sourceRef:
        kind: HelmRepository
        name: cilium        # Must match the HelmRepository name from step 2
        namespace: flux-system # Must match the HelmRepository namespace from step 2
      interval: 5m
  # --- CRD Management by Helm ---
  install:
    remediation:
      retries: 5 # More retries can help with CRD readiness
    crds: CreateReplace # Helm will install/upgrade CRDs from the chart
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    crds: CreateReplace
  # ------------------------------
  # --- Cilium Configuration Values ---
  # These are examples for k3s, you WILL need to adjust them
  values:
    # --- K3s Specifics (Important!) ---
    k8sServiceHost: "127.0.0.1" # For single-node k3s, or the IP of your k3s server
    k8sServicePort: 6443       # Default k3s API server port
    kubeProxyReplacement: "strict" # Recommended for most Cilium installs
    # If you're running k3s with flannel (default) and want Cilium to take over CNI:
    # cni:
    #   install: true
    #   uninstall: false # Don't let Cilium uninstall existing CNI on its own uninstall
    #   binPath: /var/lib/rancher/k3s/data/current/bin # k3s CNI bin path
    #   confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d # k3s CNI conf path

    # If k3s was started with --flannel-backend=none, Cilium can use standard CNI paths
    # cni:
    #  install: true

    # --- Operator and Agent ---
    operator:
      replicas: 1 # For smaller clusters
    # --- Hubble (Optional Observability) ---
    hubble:
      enabled: true # Set to false if you don't need Hubble UI/Relay initially
      relay:
        enabled: true
      ui:
        enabled: true
    # --- Other common values ---
    # ipam:
    #   mode: "kubernetes"
    # bgpControlPlane:
    #   enabled: false # Set to true if you use BGP