# clusters/k3s-home/infrastructure/01-cilium/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium # Main release name
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.17.2"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  # CRITICAL: Tell Helm install/upgrade to SKIP CRD handling
  install:
    skipCRDs: true
    remediation:
      retries: 3
  upgrade:
    skipCRDs: true
    remediation:
      retries: 3
  # CRITICAL: Also disable via values if the chart uses it
  values:
    crds:
      enabled: false # Tell the chart logic itself not to manage CRDs
    # --- All your other BGP, Ingress, Hubble values below ---
    kubeProxyReplacement: strict
    bgpControlPlane:
      enabled: true
    loadBalancer:
       mode: dsr
    l2announcements:
      enabled: false
    ingressController:
      enabled: true
      ingressClassResource:
         name: cilium
         default: true
         controllerValue: "io.cilium/ingress-controller"
      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.10.40"
          # bgp: enabled # Probably not needed if BGP CP handles LB IPs
      loadbalancerMode: dedicated
    gatewayAPI:
      enabled: false
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    k8sClientRateLimit:
      qps: 50
      burst: 200
    operator:
      rollOutPods: true
    rollOutCiliumPods: true