apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  # Reconcile the release every minute
  interval: 1m

  chart:
    spec:
      chart: cilium
      version: "1.17.3"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      # Refresh the chart index every minute
      interval: 1m
      # Force an upgrade on each reconcile, even if the chart version didn't change
      reconcileStrategy: Latest

  install:
    remediation:
      retries: 5
    crds: CreateReplace

  upgrade:
    # Force a replacement-style upgrade on each reconcile
    force: true
    remediation:
      retries: 5
      remediateLastFailure: true
    crds: CreateReplace

  values:
    # K3s API endpoint
    k8sServiceHost: "192.168.10.30"
    k8sServicePort: 6443
    kubeProxyReplacement: "false"

    # Make Cilium the exclusive CNI
    cni:
      install: true
      exclusive: true
      binPath: /var/lib/rancher/k3s/data/current/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d

    # Ensure the operator always runs one replica
    operator:
      replicas: 1

    # (Optional) Hubble observability
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
