# clusters/k3s-home/infrastructure/01-cilium/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      # UPGRADING to a version that properly supports these Helm values
      version: "1.16.0-pre.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }
  values:
    # Base K3s/CNI settings
    k8sServiceHost: "192.168.10.30"
    k8sServicePort: 6443
    cni:
      install: true
      exclusive: true
      binPath: /var/lib/rancher/k3s/data/current/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
    
    # Core Features
    kubeProxyReplacement: true
    operator: { replicas: 1 }
    gatewayAPI: { enabled: true }
    loadBalancer:
      mode: "dsr"
      l7: { backend: "envoy" }
    hubble:
      enabled: true
      ui: { enabled: true }
      relay: { enabled: true }

    # --- BGP & IPAM Configuration for v1.16+ ---
    bgpControlPlane:
      enabled: true
      
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]

    # This top-level block defines BGP policies and peers
    bgp:
      enabled: true
      # This enables the announcement of LoadBalancer IPs
      announce:
        loadBalancerIPs: true
      # This defines the peering relationship with your router
      peers:
        - name: udm-se-peer
          peerAddress: "192.168.1.1" # Your UDM SE's IP
          peerAsn: 64513           # Your UDM SE's ASN
          localAsn: 64512          # Your K3s cluster's ASN
          # Apply this peering to nodes with the 'bgp=enabled' label
          nodeSelector:
            matchLabels:
              bgp: enabled

    # This top-level block defines L2 announcements
    l2announcements:
      enabled: true
      # This policy links L2 announcements to the IP pool below
      policies:
        - name: primary-l2-policy
          ipPools:
          - name: primary-pool
          interfaces:
            # Use regex to match your USB network interfaces
            - "^enx.+"
          # Apply this policy to all nodes
          nodeSelector:
            matchLabels: {}

    # This top-level block defines the IP pool for your LoadBalancer services
    ipamPools:
      enabled: true
      pools:
        - name: primary-pool
          cidrs:
            - cidr: "192.168.10.230/28"
