apiVersion: helm.toolkit.fluxcd.io/v2beta2 # Or v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: "1.15.3" # Or your desired valid version
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    crds: CreateReplace
  # --- Corrected Cilium Configuration Values ---
  values:
    # --- K3s Specifics (Important!) ---
    k8sServiceHost: "192.168.10.30" # Your master IP
    k8sServicePort: 6443       # Default k3s API server port
    kubeProxyReplacement: "strict" # Keep this

    # --- Cilium CNI Configuration (because Flannel is removed) ---
    cni:
      install: true     # Tell Cilium to install its CNI config file
      exclusive: true   # IMPORTANT: Tell Cilium it's the exclusive CNI now
      # binPath/confPath often detected correctly when exclusive=true,
      # but specifying them doesn't hurt for K3s.
      binPath: /var/lib/rancher/k3s/data/current/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
      # REMOVED uninstall: true - it's not needed or effective here

    # --- Operator and Agent ---
    operator:
      replicas: 1 # For smaller clusters
    # --- Hubble (Optional Observability) ---
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    # --- Other common values ---
    # ipam:
    #   mode: "kubernetes" # Default is cluster-pool, which is usually fine
    # bgpControlPlane:
    #   enabled: false