apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: "1.17.3"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 15m
      reconcileStrategy: ChartVersion
  install:
    remediation:
      retries: 5
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    crds: CreateReplace

  # IMPORTANT: Define the final desired state values here
  values:
    # ==========================================
    # === ADD THESE SECTIONS FOR RBAC/SA ===
    # ==========================================
    rbac:
      create: true # Ensure Roles/ClusterRoles and Bindings are created
    serviceAccounts:
      cilium: # For the agent pods
        create: true
        name: cilium # Optional: specify name if needed, usually default is fine
      operator: # For the operator pods
        create: true
        name: cilium-operator # Optional: specify name if needed, usually default is fine
    # ==========================================
    # === Existing values below ===
    # ==========================================

    # == Base K3s/CNI settings ==
    k8sServiceHost: "192.168.10.30"
    k8sServicePort: 6443
    cni:
      install: true
      exclusive: true
      binPath: /var/lib/rancher/k3s/data/current/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
    operator:
      replicas: 1

    # == Kube-Proxy Replacement ==
    kubeProxyReplacement: true

    # == Native Routing (Recommended for DSR) ==
    tunnel: disabled # Explicitly disable tunneling
    routingMode: native # Use native routing
    autoDirectNodeRoutes: true # Often needed with native routing

    # == BGP Control Plane ==
    bgpControlPlane:
      enabled: true

    # == Load Balancing Features ==
    loadBalancer:
      mode: dsr
    l2announcements:
      enabled: true
    serviceExternalIPs:
      enabled: true

    # == Ingress Controller ==
    ingressController:
      enabled: true
      loadbalancerMode: dedicated
      service:
        type: LoadBalancer

    # == Hubble Observability (Optional but Recommended) ==
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_app,destination_ip,destination_namespace,destination_app,traffic_direction