# clusters/k3s-home/infrastructure/01-cilium/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
#  - ip-pool.yaml          # <<< CRD Instance
#  - bgp-peering.yaml      # <<< CRD Instance (Uncommented)
  - helmrelease.yaml        # <<< Main HelmRelease (skips CRDs)