apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  # - namespace.yaml
  - helmrelease.yaml
  - helmrepository.yaml
  - ip-pool.yaml
  - bgp-peering.yaml
