apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement-policy
spec:
  # Announce all LoadBalancer services
  serviceSelector:
    matchLabels: {}
  # Use all nodes for L2 announcements
  nodeSelector:
    matchLabels: {}
  # Specify which interfaces to use for announcements
  interfaces:
  - ^eth[0-9]+
  - ^ens[0-9]+
  - ^eno[0-9]+
  # Enable load balancing across nodes
  loadBalancerIPs: true