apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement-policy
spec:
  # Announce all LoadBalancer services
  serviceSelector:
    matchLabels: {}
  # Use all nodes for L2 announcements
  nodeSelector:
    matchLabels: {}
  # Specify which interfaces to use for announcements
  # Only use the USB 2.5Gbe dongles (enx*)
  interfaces:
  - ^enx[a-f0-9]+
  # Enable load balancing across nodes
  # loadBalancerIPs: true