# clusters/k3s-home/infrastructure/01-cilium/l2-announcement-policy.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement-policy
spec:
  # CHANGED: This is the modern way to select IPs for announcement.
  # It directly links this policy to the IP Pool you defined.
  ipPoolSelector:
    matchLabels:
      # This label is automatically added to your CiliumLoadBalancerIPPool
      "io.cilium.ipam.pool": "first-pool"

  # Use all nodes for L2 announcements (this is fine for a home lab)
  nodeSelector:
    matchLabels: {}

  # Your interface selection is perfect, keep it.
  interfaces:
  - ^enx[a-f0-9]+