apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auth
  namespace: flux-system
spec:
  interval: 30m
  path: ./clusters/k3s-home/apps/auth
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-runtime
    - name: sources
  decryption:
    provider: sops
    secretRef:
      name: sops-age