apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-runtime  # Needs storage classes defined
  path: ./clusters/k3s-home/apps/longhorn/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 15m
  retryInterval: 2m
  timeout: 10m
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: longhorn-manager
      namespace: longhorn-system
    - apiVersion: apps/v1
      kind: Deployment
      name: longhorn-ui
      namespace: longhorn-system