apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-system
  namespace: flux-system
spec:
  targetNamespace: longhorn-system
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  path: ./clusters/k3s-home/apps/longhorn-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn
  wait: true