# clusters/k3s-home/apps/media-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/k3s-home/apps/media
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
