apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:

  # Allow up to 15 minutes for all Helm actions
  timeout: 15m0s
  interval: 5m

  chart:
    spec:
      chart: cilium
      version: "1.17.2"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 15m
      reconcileStrategy: ChartVersion

  install:
    # Ensure CRDs are created or replaced on install
    crds: CreateReplace
    remediation:
      retries: 5

  upgrade:
    # Ensure CRDs are created or replaced on upgrade
    crds: CreateReplace
    # Allow upgrade step up to 15 minutes
    timeout: 15m0s
    # Don’t wait on pods or jobs—let CRDs land first
    disableWait: true
    disableWaitForJobs: true
    remediation:
      retries: 5
      remediateLastFailure: true

# clusters/k3s-home/infrastructure/01-cilium/helmrelease.yaml
# ... (spec section remains the same) ...
  values:
    # RBAC / ServiceAccounts (unchanged)
    rbac:
      create: true
    serviceAccounts:
      cilium:
        create: true
        name: cilium
      operator:
        create: true
        name: cilium-operator

    # Base K3s/CNI settings (unchanged)
    k8sServiceHost: "192.168.10.30"
    k8sServicePort: 6443
    cni:
      install: true
      exclusive: true
      binPath: /var/lib/rancher/k3s/data/current/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d

    operator:
      replicas: 1

    # --- CORE CHANGES ARE HERE ---

    # Core features
    kubeProxyReplacement: true
    bgpControlPlane:
      enabled: true

    # NEW: Enable Gateway API support
    gatewayAPI:
      enabled: true

    # CHANGED: Use DSR mode for better performance with BGP
    loadBalancer:
      mode: "dsr"
      l7:
        backend: "envoy" # Required for Gateway API

    # NEW: Enable L2 announcements
    l2announcements:
      enabled: true

    # REMOVED/DISABLED: We are disabling the legacy Ingress Controller
    ingressController:
      enabled: false

    # REMOVED: These are not needed for the BGP LoadBalancer model
    # serviceExternalIPs:
    #   enabled: false
    # externalIPs:
    #   enabled: false

    # Hubble remains the same
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_app,destination_ip,destination_namespace,destination_app,traffic_direction
