---
# Intel Optane NVMe PVs - Ultra Performance Tier
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-optane-1
  labels:
    type: local-ssd
    node: k3s3
    tier: ultra-performance
    storage-type: optane
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/optane-1/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-optane-2
  labels:
    type: local-ssd
    node: k3s3
    tier: ultra-performance
    storage-type: optane
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/optane-2/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
# Samsung 980 PRO NVMe PVs - High Performance Tier
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-nvme-1
  labels:
    type: local-ssd
    node: k3s3
    tier: high-performance
    storage-type: nvme
spec:
  capacity:
    storage: 900Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/nvme-1/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-nvme-2
  labels:
    type: local-ssd
    node: k3s3
    tier: high-performance
    storage-type: nvme
spec:
  capacity:
    storage: 900Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/nvme-2/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
# SAS SSDs - Standard Performance Tier
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-ssd-1
  labels:
    type: local-ssd
    node: k3s3
    tier: standard-performance
    storage-type: sas-ssd
spec:
  capacity:
    storage: 350Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/ssd-1/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-ssd-2
  labels:
    type: local-ssd
    node: k3s3
    tier: standard-performance
    storage-type: sas-ssd
spec:
  capacity:
    storage: 350Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/ssd-2/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-ssd-3
  labels:
    type: local-ssd
    node: k3s3
    tier: standard-performance
    storage-type: sas-ssd
spec:
  capacity:
    storage: 350Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/ssd-3/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-ssd-4
  labels:
    type: local-ssd
    node: k3s3
    tier: standard-performance
    storage-type: sas-ssd
spec:
  capacity:
    storage: 350Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/ssd-4/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-ssd-5
  labels:
    type: local-ssd
    node: k3s3
    tier: standard-performance
    storage-type: sas-ssd
spec:
  capacity:
    storage: 350Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/ssd-5/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-ssd-6
  labels:
    type: local-ssd
    node: k3s3
    tier: standard-performance
    storage-type: sas-ssd
spec:
  capacity:
    storage: 350Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/ssd-6/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s3-ssd-7
  labels:
    type: local-ssd
    node: k3s3
    tier: standard-performance
    storage-type: sas-ssd
spec:
  capacity:
    storage: 350Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-ssd
  local:
    path: /mnt/ssd-7/k8s-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s3