apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s-at-home.yaml
  - helmrepository.yaml
  - bjw-s.yaml
  - authentik.yaml
  - bitnami.yaml
  - longhorn-helmrepository.yaml
  - velero-helmrepository.yaml
  - prometheus-community-helmrepository.yaml
  - grafana-helmrepository.yaml
  - nvidia-dcgm-helmrepository.yaml