apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    # controller: # REMOVED/COMMENTED from top level
    #   enabled: true
    #   type: deployment

    envFrom:
    - configMapRef:
        name: rr-env

    image:
      repository: lscr.io/linuxserver/radarr
      tag: latest

    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-pvc
      data:
        enabled: true
        existingClaim: k3s-data-pvc

    service:
      main:
        controller: # <<< ADDED under service.main
          enabled: true
          type: deployment
        ports:
          http:
            port: 7878