# clusters/k3s-home/apps/media/radarr/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      # --- TRY A SLIGHTLY OLDER VERSION ---
      version: 3.7.0
      # --- END VERSION CHANGE ---
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    # --- Using top-level controller based on latest standards ---
    controller:
      enabled: true
      type: deployment
    # --- END CONTROLLER BLOCK ---

    envFrom:
    - configMapRef:
        name: rr-env

    image:
      repository: lscr.io/linuxserver/radarr
      tag: latest

    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-pvc
      data:
        enabled: true
        existingClaim: k3s-data-pvc

    service:
      main:
        # NO controller block here
        ports:
          http:
            port: 7878