apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion

  values:
    envFrom:
      - configMapRef:
          name: rr-env

    image:
      repository: lscr.io/linuxserver/radarr
      tag: latest

    controllers:
      main:
        enabled: true
        type: deployment

    service:
      main:
        controller: main    # ← must be a string, not an object
        ports:
          http:
            port: 7878

    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-pvc
      data:
        enabled: true
        existingClaim: k3s-data-pvc
