---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-quota
  namespace: media
spec:
  hard:
    requests.nvidia.com/gpu: "0"  # Media namespace uses Intel GPU only
    limits.nvidia.com/gpu: "0"
    requests.gpu.intel.com/i915: "10"  # Full access to Intel GPU shares
    limits.gpu.intel.com/i915: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-quota
  namespace: ai
spec:
  hard:
    requests.nvidia.com/gpu: "1"  # AI namespace has access to NVIDIA GPU
    limits.nvidia.com/gpu: "1"
    requests.gpu.intel.com/i915: "0"  # No Intel GPU access
    limits.gpu.intel.com/i915: "0"