apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: longhorn-http-route
  namespace: longhorn-system
spec:
  parentRefs:
  - name: main-gateway
    namespace: networking
    sectionName: https
  hostnames:
  - "longhorn.fletcherlabs.net"
  rules:
  - backendRefs:
    - name: longhorn-frontend
      port: 80