# Daily local backups for critical namespaces
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: critical-daily-local
  namespace: velero
spec:
  schedule: "0 2 * * *"  # 2 AM daily
  template:
    includedNamespaces:
    - authentik
    # - longhorn-system  # Removed - Longhorn no longer in use
    - flux-system
    - media
    - ai
    - monitoring  # Added monitoring namespace
    storageLocation: minio-local
    # volumeSnapshotLocations:  # Disabled - local-path doesn't support snapshots
    # - local-path-csi
    ttl: "168h"  # Retain for 7 days
---
# All namespaces backup weekly
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: all-namespaces-weekly-local
  namespace: velero
spec:
  schedule: "0 3 * * 0"  # 3 AM every Sunday
  template:
    storageLocation: minio-local
    # volumeSnapshotLocations:  # Disabled - local-path doesn't support snapshots
    # - local-path-csi
    ttl: "720h"  # Retain for 30 days