# Weekly offsite backups for critical namespaces
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: critical-weekly-offsite
  namespace: velero
spec:
  schedule: "0 4 * * 0"  # 4 AM every Sunday
  paused: true  # Pause until B2 is configured
  template:
    includedNamespaces:
    - authentik
    # - longhorn-system  # Removed - Longhorn no longer in use
    - flux-system
    - media
    - ai
    - monitoring  # Added monitoring namespace
    storageLocation: b2-offsite
    snapshotVolumes: false  # B2 doesn't support volume snapshots
    ttl: "2160h"  # Retain for 90 days
---
# Monthly full backup offsite
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: all-namespaces-monthly-offsite
  namespace: velero
spec:
  schedule: "0 5 1 * *"  # 5 AM on the 1st of each month
  paused: true  # Pause until B2 is configured
  template:
    storageLocation: b2-offsite
    snapshotVolumes: false  # B2 doesn't support volume snapshots
    ttl: "8760h"  # Retain for 1 year