apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy-prometheus
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.7.1"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      existingSecret: oauth2-proxy-prometheus-secret
      configFile: |-
        email_domains = [ "*" ]
        upstreams = [ "http://kube-prometheus-stack-prometheus:9090" ]
        provider = "oidc"
        oidc_issuer_url = "https://authentik.fletcherlabs.net/application/o/prometheus/"
        redirect_url = "https://prometheus.fletcherlabs.net/oauth2/callback"
        cookie_secure = true
        cookie_domains = [".fletcherlabs.net"]
        cookie_expire = "24h"
        cookie_refresh = "1h"
        skip_provider_button = true
        pass_authorization_header = true
        pass_access_token = true
        pass_user_headers = true
        set_authorization_header = true
        set_xauthrequest = true
        silence_ping_logging = true
        
    # Use correct image to avoid rate limits
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.6.0
      
    service:
      type: ClusterIP
      portNumber: 80
      
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
        
    replicaCount: 2
    
    # Pod anti-affinity for HA
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - oauth2-proxy
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - oauth2-proxy-prometheus
              topologyKey: kubernetes.io/hostname
    
    # Security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 2000
      fsGroup: 2000
      
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 2000