apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-prometheus-secret
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Me3UGrChSZqqjP6d1GmtUpgdAhZhA/tF/5qRV1h/7IaHs1P7K/WL5LutvdVRLzX2Xv5HKSyXTnVWU1ZHHqh5MzbnQQ==,iv:+hxc0yTEbp+1TpqBs0HYuhm2CE8rgWXfLS/s/cXcSWQ=,tag:rjEYwYyaFmtw9BLr6oX+Cw==,type:comment]
    client-id: ENC[AES256_GCM,data:Q9Snyo/lBMVU0g==,iv:uP6zy/+MDN0uHqXkQRY3OAwhJnXQT0+9bxKHaUKS+30=,tag:HDuGNoDwQOsDFSi84XYDeA==,type:str]
    client-secret: ENC[AES256_GCM,data:n1z8fo5a2qK2mekOFMFj5IPPIcv4AZVxcfQOQuS9LOIw5TdS1BC+yK5cP33p3Rzj0w==,iv:NHD3X9Jtqxh+E9SCCsin6RLBXRtTZuQ6yndkGmywFgA=,tag:zVSQid4UrlxDHqSSPGQaWw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:07kE1C8Kg0I+KrVOxP6AS1qcEbJOOBUHSEQBU15AKdk=,iv:8uugRk6qXtiBs0cUGcNCzwPDlm/R6nN4LWavrQOr0rM=,tag:lo6CR7Moeg3nlDUuqmEekw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ldyv96p8fpku638mlhgkzv5hjtjyc9krfwnqnx3drqvaf4jq3vyqgxurr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SEFTd0k3dEdPeENoajZE
            MDlBZWlhOW5JSmwxR2VDSHNpN1JRSFA1L3dvCjA4RHV4Z3FoVmdvajZXL0Urdmpa
            ZHBJV2JNMk9nc2xvTVdIa2lYUklhZ3MKLS0tIGVKY2VIMXZnVXBwUUN3MEhVdmxv
            cExValdMMm0xQnFEVGdWVnNaY2xpYWMKiPJkgl+h5VhdE47/ooLJge/UOhITz+5Z
            laNyjYFVtebjG25rtRwyOWtF0DaBBGOT3OqYlPlDNYDO85zqdRnERA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T00:07:55Z"
    mac: ENC[AES256_GCM,data:hXE2xQXoG9XzoWlvKp5vOzTnrLA1yDigMniPf3aHjXeK6BmRSSfYHrMhkAblQtU9MMOhBqJXDAOTBW307IrXZBbiZhvFq8eAv1Zw4uVxujBSsVxN/7NmyxCdY0+GLCQRBJiKP2DfJyNosIaSGulINheSey6cboEPnEMj2wZanNc=,iv:/vBJDVEHxMDlxRSMymOocKJcRpU9OrP1RJT/p0Nx4a4=,tag:e8pXpFEykFUOVaGpDEPKng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
