apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-prometheus-secret
  namespace: monitoring
type: Opaque
stringData:
  client-id: "prometheus"
  client-secret: "qnSQ4OdlnxCeXncxQVUpTjTzBMprnTuynrA7x0Li3OKvwT1v34va67KAmYcmPtDjXIrlD8vsfWuObPDq12FMKLv7ZewduGryuk2MqQfRnklquTlixolsul3v7dBODdpq"
  cookie-secret: "Y3WITsieCHGez8sFteKPRaAn42HOENf+"
