# clusters/k3s-home/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/    # This directory should contain kustomization-sources.yaml (or similar)
  - infrastructure/
  - apps/
  - layers.yaml     # This file defines the 'infrastructure' Kust which depends on 'cluster-sources'
