# clusters/k3s-home/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # This file now ONLY loads the Flux Kustomization definitions.
  # Flux will then use those definitions to orchestrate the cluster.
  - cluster-sync.yaml
  - flux-system/ # Keep this if it contains your flux-system GitRepo/Secret