apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/k3s-home/infrastructure # Points to infra CONTENT dir
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/k3s-home/apps # Points to apps CONTENT dir
  prune: true
  sourceRef: {kind: GitRepository, name: flux-system}
  dependsOn: [{name: infrastructure}]
  timeout: 5m