# clusters/k3s-home/layers.yaml

# --- Add this Kustomization if you don't have one for sources elsewhere ---
# --- Make sure it's included by your main flux-system/kustomization.yaml build file ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-sources # Name used in dependsOn below
#   namespace: flux-system
# spec:
#   interval: 10m
#   path: ./clusters/k3s-home/sources
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system # Or your GitRepository object name
#   wait: true
#   timeout: 2m
# ---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-home/infrastructure # Points to infrastructure CONTENT dir
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # Or your GitRepository object name
  # --- FIX dependsOn ---
  dependsOn:
    - name: cluster-sources # Ensure your sources Kustomization has this name
  # -------------------
  wait: true # Wait for deployments/daemonsets to be ready
  timeout: 20m # Increase timeout for Cilium
  healthChecks: # Recommended
    - apiVersion: apps/v1
      kind: Deployment
      name: cilium-operator
      namespace: kube-system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: cilium
      namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-home/apps # Points to apps CONTENT dir
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # Or your GitRepository object name
  dependsOn:
    - name: infrastructure # Depends on the infrastructure Kust above
  timeout: 5m
  # Add wait: true and healthChecks for apps too if desired