apiVersion: helm.toolkit.fluxcd.io/v2 # Use v2 as shown in your kubectl output
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3 # Make sure this is the version you intend to use
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion # Good practice to include
  values:
    envFrom:
      - configMapRef:
          name: rr-env # Ensure this ConfigMap exists in the 'media' namespace

    image:
      repository: lscr.io/linuxserver/bazarr
      tag: latest # Consider pinning to a specific version instead of 'latest'

    # Add the controller block here under service.main
    # This tells the chart HOW to run the main application (e.g., as a Deployment)
    controller:
      enabled: true # Explicitly enable the main controller
      type: deployment # Use 'deployment' or 'statefulset'
      # replicas: 1 # Default is usually 1, uncomment to override
      # strategy: RollingUpdate # Default for deployment, uncomment to override

    # Service definition - how the controller is exposed internally
    service:
      main:
        # Controller settings were moved to the top-level controller block ^^^
        # This section now primarily defines ports for the internal k8s service
        ports:
          http:
            port: 6767 # The port the container listens on

    # Ingress definition within the chart - keep disabled as you have a separate Ingress
    ingress:
      main:
        enabled: false

    # Persistence definition
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-pvc # Ensure this PVC exists in 'media' namespace
        mountPath: /config # Optional: specify mount path if needed, often defaults correctly
      data: # Assuming Bazarr needs a /data volume, adjust if necessary
        enabled: true
        existingClaim: k3s-data-pvc # Ensure this PVC exists in 'media' namespace
        mountPath: /data # Optional: specify mount path if needed