apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automatic1111-models-pvc
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 100Gi  # Space for multiple SD models