apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automatic1111-outputs-pvc
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 50Gi  # Space for generated images