#!/bin/bash
# Authentik Initial Setup Guide
# Created: 2025-06-15

echo "==================================="
echo "Authentik Initial Setup Guide"
echo "==================================="
echo ""
echo "Authentik is now deployed and accessible at:"
echo "https://authentik.fletcherlabs.net"
echo ""
echo "Initial Setup Steps:"
echo "1. Navigate to https://authentik.fletcherlabs.net in your browser"
echo "2. You'll be redirected to the initial setup flow"
echo "3. Create your admin account (remember to save credentials securely)"
echo "4. DO NOT enable 2FA at this time (per CIO directive)"
echo ""
echo "Services to Protect (Priority Order):"
echo "1. Longhorn UI - https://longhorn.fletcherlabs.net"
echo "2. Grafana - https://grafana.fletcherlabs.net"
echo "3. Prometheus - Create HTTPRoute first"
echo "4. Media services (Sonarr, Radarr, etc.)"
echo ""
echo "Current Pod Status:"
kubectl get pods -n authentik
echo ""
echo "To create OAuth2/OIDC applications:"
echo "1. Login to Authentik admin interface"
echo "2. Navigate to Applications -> Providers"
echo "3. Create OAuth2/OpenID provider for each service"
echo "4. Update service configurations with client ID/secret"
echo ""
echo "Documentation:"
echo "- Full setup guide: /home/josh/flux-k3s/docs/authentik-setup.md"
echo "- OAuth2 Proxy integration: Use for services without native OIDC support"
echo ""
echo "Remember: Keep 2FA DISABLED until 30-day stability period complete!"