apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  serviceName: loki-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: loki
    spec:
      serviceAccountName: loki
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        runAsNonRoot: true
      initContainers:
      - name: loki-permissions-fix
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Setting permissions for Loki directories..."
          chown -R 10001:10001 /var/loki
          mkdir -p /var/loki/rules /var/loki/chunks /var/loki/wal
          chown -R 10001:10001 /var/loki
          echo "Permissions set successfully"
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: storage
          mountPath: /var/loki
      containers:
      - name: loki
        image: grafana/loki:3.0.0
        args:
        - -config.file=/etc/loki/config/config.yaml
        - -target=all
        ports:
        - name: http-metrics
          containerPort: 3100
          protocol: TCP
        - name: grpc
          containerPort: 9095
          protocol: TCP
        volumeMounts:
        - mountPath: /var/loki
          name: storage
        - mountPath: /etc/loki/config
          name: loki-config
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: loki-storage-longhorn-0
      - name: loki-config
        configMap:
          name: loki