apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  serviceName: loki-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: loki
    spec:
      serviceAccountName: loki
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
        runAsNonRoot: true
      containers:
      - name: loki
        image: grafana/loki:3.0.0
        args:
        - -config.file=/etc/loki/config/config.yaml
        - -target=all
        volumeMounts:
        - mountPath: /var/loki
          name: storage
        - mountPath: /etc/loki/config
          name: loki-config
        - mountPath: /var/loki/rules
          name: rules
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: loki-storage-longhorn-0
      - name: loki-config
        configMap:
          name: loki
      - name: rules
        emptyDir: {}