apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-setup
  namespace: velero
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:latest
        command:
        - sh
        - -c
        - |
          mc alias set myminio http://minio.velero.svc.cluster.local:9000 minio changeme-minio-password-123
          mc mb myminio/velero-backups || echo "Bucket already exists"
          mc ls myminio/
      restartPolicy: Never
  backoffLimit: 1