apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    # Global defaults to remove fsGroup
    global:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        runAsNonRoot: true
        fsGroup: null
    
    # Prometheus specific overrides
    prometheus:
      prometheusSpec:
        securityContext:
          runAsUser: 1000
          runAsGroup: 2000
          runAsNonRoot: true
          fsGroup: null
        podMetadata:
          annotations:
            fsgroup-removed: "true"
    
    # AlertManager specific overrides  
    alertmanager:
      alertmanagerSpec:
        securityContext:
          runAsUser: 1000
          runAsGroup: 2000
          runAsNonRoot: true
          fsGroup: null
        podMetadata:
          annotations:
            fsgroup-removed: "true"
    
    # Grafana specific overrides
    grafana:
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        runAsNonRoot: true
        fsGroup: null
      podAnnotations:
        fsgroup-removed: "true"
    
    # Prometheus Operator
    prometheusOperator:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        fsGroup: null