apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    # Override Prometheus storage to use local-path
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        # Override security context to avoid fsGroup issues
        securityContext:
          runAsUser: 1000
          runAsGroup: 2000
          runAsNonRoot: true
          # Remove fsGroup to avoid permission issues with local-path
          fsGroup: null
    
    # Override AlertManager storage to use local-path  
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
        # Override security context
        securityContext:
          runAsUser: 1000
          runAsGroup: 2000
          runAsNonRoot: true
          # Remove fsGroup
          fsGroup: null
    
    # Override Grafana storage to use local-path
    grafana:
      persistence:
        enabled: true
        storageClassName: "local-path"
        accessModes:
          - ReadWriteOnce
        size: 10Gi
      # Grafana handles permissions differently, so we keep its defaults