apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium-crds
  namespace: kube-system
spec:
  interval: 3h
  chart:
    spec:
      chart: cilium
      version: "1.17.2"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  install:
    crds: Ignore  # Changed from CreateReplace to Ignore
  upgrade:
    crds: Ignore  # Changed from CreateReplace to Ignore
  values:
    crds:
      enabled: false  # Ensure the chart doesn’t try to manage CRDs
  retries: 3