apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium-crds
  namespace: kube-system
spec:
  interval: 3h
  chart:
    spec:
      chart: cilium
      version: "1.17.2"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system  # Changed from flux-system to kube-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  retries: 3