apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-home/cilium-crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
resources:
  - helmrepository.yaml
  - helmrelease-crds.yaml