apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: lscr.io/linuxserver/prowlarr
      tag: develop
    envFrom:
      - configMapRef:
          name: rr-env
    service:
      main:
        ports:
          http:
            port: 9696
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-pvc
