apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        pod:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - k3s2  # Balance with SABnzbd
        containers:
          main:
            enabled: true
            image:
              repository: lscr.io/linuxserver/prowlarr
              tag: latest
            envFrom:
              - configMapRef:
                  name: rr-env
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: true
    service:
      main:
        controller: main
        # Configure as ClusterIP to expose via Cilium ingress
        ports:
          http:
            port: 9696
            targetPort: 9696
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-pvc
      data:
        enabled: true
        existingClaim: k3s-data-pvc