apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prowlarr-http-route
  namespace: media
spec:
  parentRefs:
    - name: main-gateway
      namespace: networking
  hostnames:
    - "prowlarr.fletcherlabs.com"
  rules:
    - backendRefs:
        - name: prowlarr
          port: 9696