apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  interval: 5m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.14.5
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    # Only deploy on nodes with NVIDIA GPUs
    nodeSelector:
      gpu: nvidia
    # Tolerate the GPU taint if applied
    tolerations:
      - key: gpu
        operator: Equal
        value: nvidia
        effect: NoSchedule
    # Configure the plugin
    config:
      # Use external ConfigMap for configuration
      name: nvidia-device-plugin-config
    # Additional configuration for K3s
    runtimeClassName: nvidia
    extraEnv:
      - name: NVIDIA_DRIVER_ROOT
        value: "/"
      - name: NVIDIA_VISIBLE_DEVICES
        value: "all"
    extraVolumes:
      - name: nvidia-install-dir-host
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      - name: nvidia-lib
        hostPath:
          path: /usr/lib/nvidia
      - name: nvidia-bin
        hostPath:
          path: /usr/bin
    extraVolumeMounts:
      - name: nvidia-install-dir-host
        mountPath: /usr/local/nvidia
        readOnly: true
      - name: nvidia-lib
        mountPath: /usr/lib/nvidia
        readOnly: true
      - name: nvidia-bin
        mountPath: /usr/bin
        readOnly: true