apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  interval: 5m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.14.5
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    # Only deploy on nodes with NVIDIA GPUs
    nodeSelector:
      gpu: nvidia
    # Tolerate the GPU taint if applied
    tolerations:
      - key: gpu
        operator: Equal
        value: nvidia
        effect: NoSchedule
    # Configure the plugin
    config:
      # Allow multiple containers to share the GPU
      default: |-
        version: v1
        sharing:
          timeSlicing:
            resources:
              - name: nvidia.com/gpu
                replicas: 10  # Allow up to 10 containers to share each GPU