apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
data:
  recyclarr.yml: |
    # yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
    
    sonarr:
      sonarr-main:
        base_url: http://sonarr:8989
        api_key: !env_var SONARR_API_KEY
        
        delete_old_custom_formats: false
        
        quality_definition:
          type: series
    
    radarr:
      radarr-main:
        base_url: http://radarr:7878
        api_key: !env_var RADARR_API_KEY
        
        delete_old_custom_formats: false
        
        # Simple config - just sync quality definitions
        quality_definition:
          type: movie
          preferred_ratio: 1.0  # Maximum quality