apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
data:
  recyclarr.yml: |
    # yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
    
    sonarr:
      sonarr-main:
        base_url: http://sonarr:8989
        api_key: !env_var SONARR_API_KEY
        
        # Use TRaSH Guides pre-built templates
        include:
          - template: sonarr-quality-definition-series
          - template: sonarr-quality-profile-web-1080p
          - template: sonarr-custom-formats-web-1080p
    
    radarr:
      radarr-main:
        base_url: http://radarr:7878
        api_key: !env_var RADARR_API_KEY
        
        # Use TRaSH Guides pre-built templates for Remux quality
        include:
          - template: radarr-quality-definition-movie
          - template: radarr-quality-profile-remux-1080p
          - template: radarr-quality-profile-remux-2160p
          - template: radarr-custom-formats-remux-1080p
          - template: radarr-custom-formats-remux-2160p
        
        # Set quality definition to maximum
        quality_definition:
          type: movie
          preferred_ratio: 1.0