apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
data:
  recyclarr.yml: |
    # yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
    
    sonarr:
      sonarr-main:
        base_url: http://sonarr:8989
        api_key: 75d78cb4a038463fb078f522870773f3
        
        delete_old_custom_formats: false
        
        quality_profiles:
          - name: HD-1080p
        
        custom_formats:
          - trash_ids:
              # Audio
              - 3cafb66171b47f226146a0770576870f  # TrueHD ATMOS
              - 496f355514737f7d83bf7aa4d24f8169  # TrueHD
              - 2f22d89048b01681dde8afe203bf2e95  # DTS X
              - 570bc9ebecd92723d2d21500f4be314c  # DD+/E-AC-3 ATMOS
              - 1c1a4c5e823891c75bc50380a6866f73  # DTS-ES
              - 240770601cc226190c367ef59aba7463  # DD+
              - c2998bd0d90ed5621d8df281e839436e  # DD
            assign_scores_to:
              - name: HD-1080p
    
    radarr:
      radarr-main:
        base_url: http://radarr:7878
        api_key: 1d388bedec144460bedaf3f8a5d8257a
        
        delete_old_custom_formats: false
        
        quality_profiles:
          - name: HD-1080p
        
        custom_formats:
          - trash_ids:
              # Audio
              - 3cafb66171b47f226146a0770576870f  # TrueHD ATMOS
              - 496f355514737f7d83bf7aa4d24f8169  # TrueHD
              - 2f22d89048b01681dde8afe203bf2e95  # DTS X
              - 570bc9ebecd92723d2d21500f4be314c  # DD+/E-AC-3 ATMOS
              - 1c1a4c5e823891c75bc50380a6866f73  # DTS-ES
              - 240770601cc226190c367ef59aba7463  # DD+
              - c2998bd0d90ed5621d8df281e839436e  # DD
              # HDR
              - e23edd2482476e595fb990b12e7c609c  # DV HDR10
              - 58d6a88f13e2db7f5059c41047876f00  # DV
              - 55d53828b9d81cbe20b02efd00aa0efd  # DV HLG
              - a3e19f8f627608af0211acd02bf89735  # DV SDR
              - b974a6cd08c1066250f1f177d7aa1225  # HDR10+
              - dfb86d5941bc9075d6af23b09c2aeecd  # HDR10
              - e61e28db95d22bedcadf030b8f156d96  # HDR
              - 2a4d9069cc1fe3242ff9bdaebed239bb  # HDR (undefined)
              - 08d6d8834ad9ec87b1dc7ec8148e7a1f  # PQ
              - 9364dd386c9b4a1100dde8264690add7  # HLG
            assign_scores_to:
              - name: HD-1080p