apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
data:
  recyclarr.yml: |
    # Recyclarr Configuration Template
    # For full config guide see: https://recyclarr.dev/wiki/yaml/config-reference/
    
    sonarr:
      # Add your Sonarr instance(s) here
      sonarr-main:
        base_url: http://sonarr:8989
        api_key: YOUR_SONARR_API_KEY  # Get from Sonarr Settings -> General -> API Key
        
        quality_profiles:
          - trash_ids:
              # HD/SD Quality Profiles
              - d1498e7d189c0395d8da48a89c890f1f  # HD Bluray + WEB
            quality_profile:
              name: HD-1080p
        
        custom_formats:
          - trash_ids:
              # Audio
              - 3cafb66171b47f226146a0770576870f  # TrueHD ATMOS
              - 496f355514737f7d83bf7aa4d24f8169  # TrueHD
              - 2f22d89048b01681dde8afe203bf2e95  # DTS X
              - 570bc9ebecd92723d2d21500f4be314c  # DD+/E-AC-3 ATMOS
              - 1c1a4c5e823891c75bc50380a6866f73  # DTS-ES
              - 240770601cc226190c367ef59aba7463  # DD+
              - c2998bd0d90ed5621d8df281e839436e  # DD
            quality_profiles:
              - name: HD-1080p
    
    radarr:
      # Add your Radarr instance(s) here
      radarr-main:
        base_url: http://radarr:7878
        api_key: YOUR_RADARR_API_KEY  # Get from Radarr Settings -> General -> API Key
        
        quality_profiles:
          - trash_ids:
              # Movie Quality Profiles
              - c20f169ef63c5f40c2def54abaf4438e  # Remux-1080p
              - c20c8647f2746a1f4c4262b0fbbeeeae  # Remux-2160p
            quality_profile:
              name: Remux-1080p
        
        custom_formats:
          - trash_ids:
              # Audio
              - 3cafb66171b47f226146a0770576870f  # TrueHD ATMOS
              - 496f355514737f7d83bf7aa4d24f8169  # TrueHD
              - 2f22d89048b01681dde8afe203bf2e95  # DTS X
              - 570bc9ebecd92723d2d21500f4be314c  # DD+/E-AC-3 ATMOS
              - 1c1a4c5e823891c75bc50380a6866f73  # DTS-ES
              - 240770601cc226190c367ef59aba7463  # DD+
              - c2998bd0d90ed5621d8df281e839436e  # DD
            quality_profiles:
              - name: Remux-1080p