# IMPORTANT: This file should be encrypted with SOPS before committing to Git
# Run: sops -e -i secret-authentik.yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:OqHFnSghYrz4eg8hw9by5wDQdoyhOtVE6pcnLgh7pkPrsp5ykWhiv+zmcpY=,iv:NxUsHbO8mRSZ5LN7e4WvBBag3g7y3DM0QGc8i5ooAl8=,tag:oNqGuYgzOulzRCAlHNgWYA==,type:str]
    AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:EO3VCi5e1yVlrw01aIs2hM0R6+h9bbT5Qrhj9ShMFU8=,iv:qAO8dqFSGDXdAXpd6M8akgjaN8sjOLtKs4/RkMk2l1M=,tag:weClGlipKwwiVAqo/NFTPg==,type:str]
    POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:iOq/HSVePP6sp0+2bQXj6DU6+uwIhFJBVW05TkoM1yY=,iv:UoG4J2T4RdUeHPcle5dKjx6A0u184PpxiaeAHovKEPs=,tag:Y0e2R2hjnKrHMiUr4O8vpQ==,type:str]
    AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:LJi9m2/F/BazHTPR332LCXgKe9bLG3gkAO+6wzRs0lY=,iv:/yuYzghKX397mQjkIS3efer5pYS/7/j4hlUyYys+AJ0=,tag:JzI5rIXxtp5KSZh053JVug==,type:str]
    values.yaml: ENC[AES256_GCM,data:fy4W14Amgp/v9CKhQb4ts5tt/70Tvu45H9orcV9AS/tVrkDfRwh4hFg=,iv:48ed1Jx7+MfDgdQDdKRmE0442K47NnFlgjJ/alJQMHg=,tag:PVFlI4IHylDl+A3c27Vstw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ldyv96p8fpku638mlhgkzv5hjtjyc9krfwnqnx3drqvaf4jq3vyqgxurr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMWhUdWRvb1UxbCtoS2ln
            aCtEbWFJMmxTWUZQZHd1TjZjeDYrSDJsUEdzCngvODdyc1BCN21NRThaSjkzdEVM
            VVpIckF5bnRYQWl5dWhVK2taeWJoQ0UKLS0tIGVYcmRiUGpEMHZ2NEVadFMydmJ4
            aGk3V1o4RERJWGlpbTVLNmlRNmJYcTgKi3yqtgjRwVO9CMdGS8+UHpI0LL3YKUzR
            aatNzlwLQDv6eeUDSF/3QBu9sEB3Iek5PBCVSGk0EjAOmQhLOntQMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-13T07:18:43Z"
    mac: ENC[AES256_GCM,data:lrU9d0kizc+vFFsMqa65an7TNmuwFPCXqfq2FVV80GRMUd4ASTC74zkKZzMrLSK/iwwyvUTW6Srsx2xLQBtXi79Qnk8jRhTTsnNVmLY2208MqKOK9WhaqlCEFxGzY1bNMUFhYU9d1M39e25JM+d8/F06RETbyfMXh0q6KNeb6/M=,iv:1Yrx+WRoAiHDXVqtkjqLG4ZyIu1iP79LbOqigXyt1/E=,tag:P579hPDCdKrKwbIKY0giNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
