# IMPORTANT: This file should be encrypted with SOPS before committing to Git
# Run: sops -e -i secret-authentik.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "NcGGFGtYkKqTJd3bh9OOgvnKNKA33TNJy6ntTPeg+u4="
  AUTHENTIK_POSTGRES_PASSWORD: "TOtREQVNTNc4149HvuM6GQxrNK7s7ftv"
  POSTGRES_ADMIN_PASSWORD: "Ur6vjwJvfxXaFJfeAyGxiHanXaeB8hD8"
  AUTHENTIK_REDIS_PASSWORD: "7IO1VqufeWWUCgz6UnhXG48oGS03AoYz"
  values.yaml: |
    # Additional sensitive values can go here